@isTest
public with sharing class AccountSearchAddressControllerTest {
    @IsTest
    static void givenZipCodeWhenFetchAddressThenReturnSuccess(){}

    @IsTest
    static void givenInvalidZipCodeWhenFetchAddressThenThrowAnException(){}

    @IsTest
    static void givenAccountWithAddressesWhenSaveAccountThenUpdateRecord(){}

    @isTest
    static void givenInvalidAccountWithAddressesWhenSaveAccountThenThrowAnException(){}

}